api_platform:
    title: Book Aarhus API Service
    description: 'API Service for Book Aarhus'
    version: 1.0
    defaults:
        route_prefix: 'v1'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    show_webby: false
    doctrine:
        enabled: true
    openapi:
        contact:
            name: ITKDev
            email: itkdev@mkb.aarhus.dk
        backward_compatibility_layer: true
        license:
            name: MIT
    path_segment_name_generator: api_platform.path_segment_name_generator.dash
    graphql:
        enabled: false
        graphiql:
            enabled: false
        graphql_playground:
            enabled: false
    enable_re_doc: false
