doctrine:
    dbal:
        default_connection: default
        types:
            # https://www.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/known-vendor-issues.html#microsoft-sql-server
            time: 'Doctrine\DBAL\Types\VarDateTimeType'
            datetime: App\Doctrine\Extensions\DBAL\Types\UTCDateTimeType
            datetime_immutable: App\Doctrine\Extensions\DBAL\Types\UTCDateTimeImmutableType
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
                driver: 'pdo_mysql'

                # IMPORTANT: You MUST configure your server version,
                # either here or in the DATABASE_URL env var (see .env file)
                #server_version: '13'

    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: true

        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: true
                mappings:
                    App:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity/Main'
                        prefix: 'App\Entity\Main'
                        alias: App

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
