openapi: 3.0.3
info:
  title: 'Book Aarhus API Service'
  description: 'API Service for Book Aarhus'
  license:
    name: MIT
  version: '1'
servers:
  -
    url: /
    description: ''
paths:
  /v1/busy-intervals:
    get:
      operationId: get-v1-busy-intervals
      tags:
        - BusyInterval
      responses:
        200:
          description: OK
          content:
            application/ld+json:
              examples: null
          headers: {  }
      summary: 'Retrieves busy intervals.'
      description: 'Retrieves busy intervals.'
      parameters:
        -
          name: resources
          in: query
          description: 'Array of resources to request busy intervals for.'
          required: true
          deprecated: false
          allowEmptyValue: false
          schema:
            type: array
            items:
              type: string
              example: test@bookaarhus.local.itkdev.dk
          style: form
          explode: false
          allowReserved: false
        -
          name: dateStart
          in: query
          description: 'Start time for the search interval (DateTime. Expected format: "2022-05-30T17:32:28Z")'
          required: true
          deprecated: false
          allowEmptyValue: false
          schema:
            type: string
            format: date-time
            example: '2022-05-30T17:32:28Z'
          style: form
          explode: false
          allowReserved: false
        -
          name: dateEnd
          in: query
          description: 'End time for the search interval (DateTime. Expected format: "2022-05-30T17:32:28Z")'
          required: true
          deprecated: false
          allowEmptyValue: false
          schema:
            type: string
            format: date-time
            example: '2022-06-22T17:32:28Z'
          style: form
          explode: false
          allowReserved: false
        -
          name: page
          in: query
          description: 'The collection page number'
          required: false
          deprecated: false
          allowEmptyValue: true
          schema:
            type: integer
            default: 1
          style: form
          explode: false
          allowReserved: false
      deprecated: false
    parameters: []
  '/v1/busy-intervals/{id}':
    get:
      operationId: getBusyIntervalItem
      tags:
        - BusyInterval
      responses:
        200:
          description: 'BusyInterval resource'
          content:
            application/ld+json:
              schema:
                $ref: '#/components/schemas/BusyInterval.jsonld'
            application/json:
              schema:
                $ref: '#/components/schemas/BusyInterval'
            text/html:
              schema:
                $ref: '#/components/schemas/BusyInterval'
        404:
          description: 'Resource not found'
      summary: 'Retrieves a BusyInterval resource.'
      description: 'Retrieves a BusyInterval resource.'
      parameters:
        -
          name: id
          in: path
          description: 'Resource identifier'
          required: true
          deprecated: false
          allowEmptyValue: false
          schema:
            type: string
          style: simple
          explode: false
          allowReserved: false
      deprecated: false
    parameters: []
components:
  schemas:
    BusyInterval:
      type: object
      properties:
        id:
          type: string
        resource:
          type: string
        startTime:
          type: string
          format: date-time
          nullable: true
        endTime:
          type: string
          format: date-time
          nullable: true
    BusyInterval.jsonld:
      type: object
      properties:
        '@id':
          readOnly: true
          type: string
        '@type':
          readOnly: true
          type: string
        '@context':
          readOnly: true
          oneOf:
            -
              type: string
            -
              type: object
              properties:
                '@vocab':
                  type: string
                hydra:
                  type: string
                  enum: ['http://www.w3.org/ns/hydra/core#']
              required:
                - '@vocab'
                - hydra
              additionalProperties: true
        id:
          type: string
        resource:
          type: string
        startTime:
          type: string
          format: date-time
          nullable: true
        endTime:
          type: string
          format: date-time
          nullable: true
  responses: {  }
  parameters: {  }
  examples: {  }
  requestBodies: {  }
  headers: {  }
  securitySchemes: {  }
security: []
tags: []
