# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    microsoft_graph_tenant_id: '%env(string:MICROSOFT_GRAPH_TENANT_ID)%'
    microsoft_graph_client_id: '%env(string:MICROSOFT_GRAPH_CLIENT_ID)%'
    microsoft_graph_service_account_name: '%env(string:MICROSOFT_GRAPH_SERVICE_ACCOUNT_NAME)%'
    microsoft_graph_service_account_username: '%env(string:MICROSOFT_GRAPH_SERVICE_ACCOUNT_USERNAME)%'
    microsoft_graph_service_account_password: '%env(string:MICROSOFT_GRAPH_SERVICE_ACCOUNT_PASSWORD)%'
    email_from_address: '%env(string:EMAIL_FROM_ADDRESS)%'
    email_admin_notification: '%env(string:ADMIN_NOTIFICATION_EMAIL)%'
    resources_list_endpoint: '%env(string:RESOURCES_LIST)%'
    resources_locations_endpoint: '%env(string:RESOURCES_LOCATIONS)%'
    resources_opening_hours_endpoint: '%env(string:RESOURCES_OPENING_HOURS)%'
    resources_holiday_opening_hours_endpoint: '%env(string: RESOURCES_HOLIDAY_OPENING_HOURS)%'
    resources_cvr_whitelist_endpoint: '%env(string:RESOURCES_CVR_WHITELIST)%'
    excluded_resources: '%env(json:APP_EXCLUDED_RESOURCES)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

        bind:
            $projectDir: '%kernel.project_dir%'
            $bindDefaultDateFormat: '%env(string:APP_DEFAULT_DATE_FORMAT)%'
            $bindNotificationTimezone: '%env(string:APP_NOTIFICATION_TIMEZONE)%'
            $bindNotificationDateFormat: '%env(string:APP_NOTIFICATION_DATE_FORMAT)%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Doctrine\ResourceExtension:
        tags:
            - { name: api_platform.doctrine.orm.query_extension.collection }
            - { name: api_platform.doctrine.orm.query_extension.item }

    App\Service\MicrosoftGraphHelperService:
        arguments:
            - '%microsoft_graph_tenant_id%'
            - '%microsoft_graph_client_id%'
            - '%microsoft_graph_service_account_username%'
            - '%microsoft_graph_service_account_password%'

    App\Service\MicrosoftGraphBookingService:
        - '%microsoft_graph_service_account_username%'
        - '%microsoft_graph_service_account_name%'

    App\Service\NotificationService:
        arguments:
            - '%email_from_address%'
            - '%email_admin_notification%'

    App\Service\ResourceService:
        arguments:
            $excludedResources: '%excluded_resources%'
            $resourceListEndpoint: '%resources_list_endpoint%'
            $resourceLocationsEndpoint: '%resources_locations_endpoint%'
            $resourceCvrWhitelistEndpoint: '%resources_cvr_whitelist_endpoint%'
            $resourceOpeningHoursEndpoint: '%resources_opening_hours_endpoint%'
            $resourceHolidayOpeningHoursEndpoint: '%resources_holiday_opening_hours_endpoint%'

    App\OpenApi\OpenApiFactory:
        decorates: 'api_platform.openapi.factory'
        arguments: ['@App\OpenApi\OpenApiFactory.inner']
        autoconfigure: false

    # Interface aliases

    App\Interface\BookingServiceInterface:
        alias: 'App\Service\MicrosoftGraphBookingService'

    App\Interface\WebformServiceInterface:
        alias: 'App\Service\WebformService'

    App\Interface\NotificationServiceInterface:
        alias: 'App\Service\NotificationService'

    App\Interface\ResourceServiceInterface:
        alias: 'App\Service\ResourceService'

    # Api Filters

    resource.search_filter:
        # https://api-platform.com/docs/core/filters/#search-filter
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments:
            [
                {
                    location: 'exact',
                    resourceName: 'partial',
                    resourceMail: 'exact',
                },
            ]
        tags: ['api_platform.filter']
        autowire: false
        autoconfigure: false
        public: false

    resource.boolean_filter:
        # https://api-platform.com/docs/core/filters/#boolean-filter
        parent: 'api_platform.doctrine.orm.boolean_filter'
        arguments:
            [
                {
                    wheelchairAccessible: ~,
                    videoConferenceEquipment: ~,
                    monitorEquipment: ~,
                    acceptanceFlow: ~,
                    catering: ~,
                    permissionBusinessPartner: ~,
                    permissionCitizen: ~,
                },
            ]
        tags: ['api_platform.filter']
        autowire: false
        autoconfigure: false
        public: false

    resource.range_filter:
        # https://api-platform.com/docs/core/filters/#range-filter
        parent: 'api_platform.doctrine.orm.range_filter'
        arguments: [{ capacity: ~ }]
        tags: ['api_platform.filter']
        autowire: false
        autoconfigure: false
        public: false

    user_booking_cache_entry.search_filter:
        # https://api-platform.com/docs/core/filters/#search-filter
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments: [{ title: 'partial' }]
        tags: ['api_platform.filter']
        autowire: false
        autoconfigure: false
        public: false

    user_booking_cache_entry.date_filter:
        parent: 'api_platform.doctrine.orm.date_filter'
        arguments: [{ start: ~, end: ~ }]
        tags: ['api_platform.filter']
        autowire: false
        autoconfigure: false
        public: false

    user_booking_cache_entry.order_filter:
        parent: 'api_platform.doctrine.orm.order_filter'
        arguments:
            $properties:
                {
                    title: ~,
                    start: ~,
                    end: ~,
                    resourceMail: ~,
                    resourceDisplayName: ~,
                }
            $orderParameterName: order
        tags: ['api_platform.filter']
        autowire: false
        autoconfigure: false
        public: false
