services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    App\Repository\Resources\AAKResourceRepository: ~

    App\Service\BookingServiceInterface:
        alias: 'App\Service\MicrosoftGraphBookingService'

    App\Service\WebformServiceInterface:
        alias: 'App\Service\WebformService'

    App\Service\NotificationServiceInterface: ~

    App\Service\MicrosoftGraphHelperService:
        arguments:
            - 'test'
            - 'test'
            - 'test@example.com'
            - 'test'

