---
resources:
  App\Entity\BusyInterval:
    itemOperations:
      get: ~
    collectionOperations:
      get:
        openapi_context:
          operationId: get-v1-busy-intervals
          description: Retrieves busy intervals.
          summary: Retrieves busy intervals.
          tags:
            - BusyInterval
          parameters:
            - schema:
                type: array
                items:
                  type: string
                  example: test@bookaarhus.local.itkdev.dk
              name: resources
              in: query
              required: true
            - schema:
                type: string
                format: date-time
                example: "2022-05-30T17:32:28Z"
              in: query
              name: dateStart
              required: true
            - schema:
                type: string
                format: date-time
                example: "2022-06-22T17:32:28Z"
              in: query
              name: dateEnd
              required: true
          responses:
            '200':
              description: OK
              content:
                application/ld+json:
                  examples:
              headers: { }
