---
resources:
  App\Entity\BusyInterval:
    itemOperations:
      get:
        controller: ApiPlatform\Core\Action\NotFoundAction
        read: false
        output: false
        openapi_context:
          description: Unsupported action.
          summary: Unsupported action.
    collectionOperations:
      get:
        openapi_context:
          operationId: get-v1-busy-intervals
          description: Retrieves busy intervals.
          summary: Retrieves busy intervals.
          tags:
            - BusyInterval
          parameters:
            - schema:
                type: array
                items:
                  type: string
                  example: test@bookaarhus.local.itkdev.dk
              name: resources
              in: query
              required: true
              description: Array of resources to request busy intervals for.
            - schema:
                type: string
                format: date-time
                example: "2022-05-30T17:32:28Z"
              in: query
              name: dateStart
              required: true
              description: "Start time for the search interval (DateTime. Expected format: \"2022-05-30T17:32:28Z\")"
            - schema:
                type: string
                format: date-time
                example: "2022-06-22T17:32:28Z"
              in: query
              name: dateEnd
              required: true
              description: "End time for the search interval (DateTime. Expected format: \"2022-05-30T17:32:28Z\")"
          responses:
            '200':
              description: OK
              content:
                application/ld+json:
                  examples:
              headers: { }
