---
resources:
  App\Entity\Main\Location:
    itemOperations:
      get:
        controller: ApiPlatform\Core\Action\NotFoundAction
        read: false
        output: false
        openapi_context:
          description: Unsupported action.
          summary: Unsupported action.
    collectionOperations:
      get:
        openapi_context:
          operationId: get-v1-locations
          description: Retrieves locations.
          summary: Retrieves locations.
          tags:
            - Location
          parameters:
          responses:
            '200':
              description: OK
              content:
                application/ld+json:
                  examples:
              headers: { }
