---
resources:
  App\Entity\Resources\AAKResource:
    attributes:
      normalization_context:
        groups: ['resource']
    shortName: 'Resource'
    itemOperations:
      get: ~
    collectionOperations:
      get:
        filters: ['resource.search_filter', 'resource.boolean_filter', 'resource.range_filter']
      get_all:
        method: GET
        path: '/resources-all'
        controller: App\Controller\GetAllResourcesController
        openapi_context:
          description: Get all resources in a minified view.
          summary: Get all resources.
          operationId: get-v1-all-resources
          tags:
            - Resource
          parameters: []
          responses:
            '200':
      get_by_email:
        method: GET
        path: '/resource-by-email/{resourceMail}'
        controller: App\Controller\GetResourceByEmailController
        openapi_context:
          description: Get a resource by email
          summary: Get a resource by email
          operationId: get-v1-resource-by-email
          tags:
            - Resource
          parameters:
            - schema:
                type: string
                format: string
                example: "test@example.com"
              in: path
              name: resourceMail
              required: true
              description: "Resource mail"
          responses:
            '200':
