---
resources:
  App\Entity\Resources\AAKResource:
    attributes:
      normalization_context:
        groups: ['resource']
    shortName: 'Resource'
    itemOperations:
      get:
    collectionOperations:
      get:
        filters: ['resource.search_filter', 'resource.boolean_filter', 'resource.range_filter']
