---
resources:
  App\Entity\Main\UserBooking:
    itemOperations:
      get: ~
      delete:
        controller: App\Controller\DeleteBookingController
        path: /user-bookings/{id}
        openapi_context:
          operationId: get-v1-booking-delete
          description: Requests deletion for a specific booking.
          summary: Requests deletion for a specific booking.
          tags:
          parameters:
            - schema:
                type: string
                format: string
                example: "AAMkADA2YjNjYzNjLThjMjAtNDA3MS05NWEwLTZhZjM2MzYxZjZmNwBGAAAAAADPMx9il/l3TpK5N7vcXYJbBwCTGBSNlZNgQKMu0+Oa3o5eAAAAAAENAACTGBSNlZNgQKMu0+Oa3o5eAAAbYXKrAAA="
              in: path
              name: id
              required: true
              description: "ID of the booking to delete"
        responses:
          '200':
            description: OK
            content:
              application/ld+json:
                examples:
            headers: { }
    collectionOperations:
      get:
        openapi_context:
          operationId: get-v1-user-bookings
          description: Retrieves user bookings.
          summary: Retrieves user bookings.
          tags:
          parameters:
            - schema:
                type: string
                format: string
                example: "1"
              in: query
              name: userId
              required: true
              description: "ID of the user to retrieve bookings for"
          responses:
            '200':
              description: OK
              content:
                application/ld+json:
                  examples:
              headers: { }
      
