---
resources:
  App\Entity\Main\UserBooking:
    itemOperations:
      get: ~
    collectionOperations:
      get:
        openapi_context:
          operationId: get-v1-user-bookings
          description: Retrieves user bookings.
          summary: Retrieves user bookings.
          tags:
          parameters:
            - schema:
                type: string
                format: string
                example: "1"
              in: query
              name: userId
              required: true
              description: "ID of the user to retrieve bookings for"
          responses:
            '200':
              description: OK
              content:
                application/ld+json:
                  examples:
              headers: { }
      post:
          openapi_context:
            operationId: get-v1-booking-delete
            description: Deletes a specific booking.
            summary: Deletes a specific booking.
            tags:
            parameters:
              - schema:
                  type: string
                  format: string
                  example: "1"
                in: query
                name: userId
                required: true
                description: "ID of the booking to request a deletion for"
            responses:
              '200':
                description: OK
                content:
                  application/ld+json:
                    examples:
                headers: { }
