---
resources:
  App\Entity\UserBooking:
    itemOperations:
      get: ~
    collectionOperations:
      get:
        openapi_context:
          operationId: get-v1-user-bookings
          description: Retrieves user bookings.
          summary: Retrieves user bookings.
          tags:
          parameters:
            - schema:
                type: string
                format: string
                example: "1"
              in: query
              name: userId
              required: true
              description: "ID of the user to retrieve bookings for"
          responses:
            '200':
              description: OK
              content:
                application/ld+json:
                  examples:
              headers: { }
      
