---
resources:
  App\Entity\BookingDelete:
    itemOperations:
      get: 
        controller: ApiPlatform\Core\Action\NotFoundAction
        read: false
        output: false
        openapi_context:
          description: Unsupported action.
          summary: Unsupported action.
    collectionOperations:
      get: 
        pagination_enabled: false
        openapi_context:
          operationId: get-v1-booking-delete
          description: Requests deletion for a specific booking.
          summary: Requests deletion for a specific booking.
          tags:
          parameters:
            - schema:
                type: string
                format: string
                example: "AAMkADA2YjNjYzNjLThjMjAtNDA3MS05NWEwLTZhZjM2MzYxZjZmNwBGAAAAAADPMx9il/l3TpK5N7vcXYJbBwCTGBSNlZNgQKMu0+Oa3o5eAAAAAAENAACTGBSNlZNgQKMu0+Oa3o5eAAAbYXKrAAA="
              in: query
              name: bookingId
              required: true
              description: "ID of the booking to retrieve details for"
          responses:
            '200':
              description: OK
              content:
                application/ld+json:
                  examples:
              headers: { }
        