---
resources:
  App\Entity\Main\BookingDetails:
    itemOperations:
      get: ~
    collectionOperations:
      get: 
        openapi_context:
          operationId: get-v1-booking-details
          description: Retrieves details on a specific booking details.
          summary: Retrieves user booking details.
          tags:
          parameters:
            - schema:
                type: string
                format: string
                example: "AAMkADA2YjNjYzNjLThjMjAtNDA3MS05NWEwLTZhZjM2MzYxZjZmNwBGAAAAAADPMx9il/l3TpK5N7vcXYJbBwCTGBSNlZNgQKMu0+Oa3o5eAAAAAAENAACTGBSNlZNgQKMu0+Oa3o5eAAAbYXKrAAA="
              in: query
              name: bookingId
              required: true
              description: "ID of the booking to retrieve details for"
          responses:
            '200':
              description: OK
              content:
                application/ld+json:
                  examples:
              headers: { }